#!/usr/bin/env bash
set -euo pipefail

# Supplement stage-2 DFNs for blank units selected around real-well dense areas.
#
# The workflow for each unit is:
#   1) build virtual well
#   2) predict virtual-well fractures
#   3) merge virtual/real seeds into a unit seed package
#   4) build the final unit DFN into the shared stage-2 result directory
#
# Parallel execution is unit-level parallelism. Per-unit prediction/package roots
# are isolated so summary files generated by legacy scripts do not race.
#
# Optional distributed sharding:
#   SHARD_COUNT=2 SHARD_INDEX=0 .../run_supplement_blank_units_from_list.sh
#   SHARD_COUNT=2 SHARD_INDEX=1 .../run_supplement_blank_units_from_list.sh
# SHARD_INDEX is zero-based. Each shard keeps the original CSV order inside its
# own subset.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

CONDA_ENV="${CONDA_ENV:-gan-dfn}"
PYTHON_CMD=(conda run -n "${CONDA_ENV}" python)

UNIT_LIST_CSV="${UNIT_LIST_CSV:-${REPO_ROOT}/record/supplement_blank_unit_candidates_130_20260606.csv}"

VIRTUAL_WELL_ROOT="${VIRTUAL_WELL_ROOT:-/data/shared/project-oil/wx数据/砂砾岩/优化阶段一/研究内容二/虚拟测井构建/虚拟测井批量生成}"
VIRTUAL_FRACTURE_WORK_ROOT="${VIRTUAL_FRACTURE_WORK_ROOT:-/data/shared/project-oil/wx数据/砂砾岩/优化阶段一/研究内容二/虚拟测井构建/虚拟裂缝预测_补充空白单元_20260606}"
UNIT_PACKAGE_WORK_ROOT="${UNIT_PACKAGE_WORK_ROOT:-/data/shared/project-oil/wx数据/砂砾岩/优化阶段一/研究内容二/单元DFN构建/单元测井裂缝_新层位重拆分/supplement_blank_units_20260606_per_unit}"
FINAL_DFN_ROOT="${FINAL_DFN_ROOT:-/data/shared/project-oil/wx数据/砂砾岩/优化阶段一/研究内容二/单元DFN构建/批量生成_新层位重拆分}"

# Use the existing full package as real seed source. For true blank units this
# contributes nothing; for real-well units that lack final DFN, it preserves any
# available measured-well seeds while adding virtual seeds.
REAL_ROOT="${REAL_ROOT:-/data/shared/project-oil/wx数据/砂砾岩/优化阶段一/研究内容二/单元DFN构建/单元测井裂缝_新层位重拆分/full_t1_t7_resplit_20260501}"

LOG_ROOT="${LOG_ROOT:-/data/shared/project-oil/wx数据/砂砾岩/优化阶段一/研究内容二/单元DFN构建/补充空白单元日志_20260606}"
STATUS_ROOT="${STATUS_ROOT:-${LOG_ROOT}/status}"

# Default to modest unit-level multiprocessing. Increase only after checking CPU,
# memory, and shared-disk IO pressure.
MAX_PARALLEL="${MAX_PARALLEL:-4}"
SKIP_EXISTING="${SKIP_EXISTING:-1}"
OVERWRITE_FINAL="${OVERWRITE_FINAL:-0}"
FAIL_FAST="${FAIL_FAST:-1}"
GPU_IDS="${GPU_IDS:-}"
OMP_NUM_THREADS="${OMP_NUM_THREADS:-2}"
MKL_NUM_THREADS="${MKL_NUM_THREADS:-2}"
OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-2}"
START_INDEX="${START_INDEX:-1}"
END_INDEX="${END_INDEX:-0}"
SHARD_COUNT="${SHARD_COUNT:-1}"
SHARD_INDEX="${SHARD_INDEX:-0}"

VIRTUAL_WELL_SCRIPT="${REPO_ROOT}/小范围DFN生成/优化阶段一/虚拟测井/generate_unit_virtual_well.py"
VIRTUAL_FRACTURE_SCRIPT="${REPO_ROOT}/小范围DFN生成/优化阶段一/虚拟裂缝预测/run_batch_virtual_well_fracture_prediction.py"
MERGE_PACKAGE_SCRIPT="${REPO_ROOT}/小范围DFN生成/优化阶段一/单元裂缝归属/merge_virtual_fractures_into_unit_packages.py"
BUILD_DFN_SCRIPT="${REPO_ROOT}/小范围DFN生成/优化阶段一/单元DFN构建/build_single_unit_dfn.py"

mkdir -p "${LOG_ROOT}" "${STATUS_ROOT}" "${VIRTUAL_FRACTURE_WORK_ROOT}" "${UNIT_PACKAGE_WORK_ROOT}" "${FINAL_DFN_ROOT}"

if [[ ! -f "${UNIT_LIST_CSV}" ]]; then
  echo "[supplement] unit list csv not found: ${UNIT_LIST_CSV}" >&2
  exit 1
fi

for required_script in "${VIRTUAL_WELL_SCRIPT}" "${VIRTUAL_FRACTURE_SCRIPT}" "${MERGE_PACKAGE_SCRIPT}" "${BUILD_DFN_SCRIPT}"; do
  if [[ ! -f "${required_script}" ]]; then
    echo "[supplement] required script not found: ${required_script}" >&2
    exit 1
  fi
done

mapfile -t UNIT_IDS < <(
  UNIT_LIST_CSV_ENV="${UNIT_LIST_CSV}" \
  START_INDEX_ENV="${START_INDEX}" \
  END_INDEX_ENV="${END_INDEX}" \
  SHARD_COUNT_ENV="${SHARD_COUNT}" \
  SHARD_INDEX_ENV="${SHARD_INDEX}" \
  python -c '
import csv
import os
from pathlib import Path

p = Path(os.environ["UNIT_LIST_CSV_ENV"])
with p.open("r", encoding="utf-8-sig", newline="") as handle:
    reader = csv.DictReader(handle)
    if not reader.fieldnames or "UnitID" not in reader.fieldnames:
        raise SystemExit(f"UnitID column not found in {p}")
    unit_ids = [str(row.get("UnitID", "")).strip() for row in reader]
unit_ids = [item for item in unit_ids if item]
if not unit_ids:
    raise SystemExit(f"UnitID column not found in {p}")
start_index = max(1, int(os.environ.get("START_INDEX_ENV", "1")))
end_index = int(os.environ.get("END_INDEX_ENV", "0"))
shard_count = max(1, int(os.environ.get("SHARD_COUNT_ENV", "1")))
shard_index = int(os.environ.get("SHARD_INDEX_ENV", "0"))
if shard_index < 0 or shard_index >= shard_count:
    raise SystemExit(f"SHARD_INDEX must be in [0, SHARD_COUNT-1], got {shard_index}/{shard_count}")
if end_index > 0:
    unit_ids = unit_ids[start_index - 1:end_index]
else:
    unit_ids = unit_ids[start_index - 1:]
if shard_count > 1:
    unit_ids = [unit_id for idx, unit_id in enumerate(unit_ids) if idx % shard_count == shard_index]
for unit_id in unit_ids:
    print(unit_id)
'
)

if [[ ${#UNIT_IDS[@]} -eq 0 ]]; then
  echo "[supplement] no units loaded from ${UNIT_LIST_CSV}" >&2
  exit 1
fi

parse_block_index() {
  local unit_id="$1"
  if [[ ! "${unit_id}" =~ ^BX([0-9]+)_BY([0-9]+)$ ]]; then
    echo "[supplement] invalid UnitID: ${unit_id}" >&2
    return 1
  fi
  echo "${BASH_REMATCH[1]} ${BASH_REMATCH[2]}"
}

gpu_for_index() {
  local index="$1"
  if [[ -z "${GPU_IDS}" ]]; then
    echo ""
    return 0
  fi
  IFS=',' read -r -a gpu_array <<< "${GPU_IDS}"
  local count="${#gpu_array[@]}"
  if [[ "${count}" -eq 0 ]]; then
    echo ""
    return 0
  fi
  local slot=$(( (index - 1) % count ))
  echo "${gpu_array[${slot}]}"
}

run_unit() {
  local unit_id="$1"
  local index="$2"
  local total="$3"
  local log_file="${LOG_ROOT}/${index}_of_${total}_${unit_id}.log"
  local status_file="${STATUS_ROOT}/${unit_id}.status"
  local final_summary="${FINAL_DFN_ROOT}/${unit_id}/unit_dfn_summary.json"
  local pred_root="${VIRTUAL_FRACTURE_WORK_ROOT}/${unit_id}"
  local package_root="${UNIT_PACKAGE_WORK_ROOT}/${unit_id}"
  local pred_docx="${pred_root}/experiment_log_${unit_id}.docx"
  local merge_docx="${package_root}/merge_log_${unit_id}.docx"
  local gpu_id
  gpu_id="$(gpu_for_index "${index}")"

  rm -f "${status_file}"
  mkdir -p "${pred_root}" "${package_root}"

  {
    echo "[unit ${index}/${total}] start ${unit_id} at $(date '+%F %T')"
    echo "[unit ${index}/${total}] log=${log_file}"
    echo "[unit ${index}/${total}] pred_root=${pred_root}"
    echo "[unit ${index}/${total}] package_root=${package_root}"
    echo "[unit ${index}/${total}] final_root=${FINAL_DFN_ROOT}"
    if [[ -n "${gpu_id}" ]]; then
      export CUDA_VISIBLE_DEVICES="${gpu_id}"
      echo "[unit ${index}/${total}] CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"
    fi
    export OMP_NUM_THREADS MKL_NUM_THREADS OPENBLAS_NUM_THREADS

    if [[ "${OVERWRITE_FINAL}" != "1" && "${SKIP_EXISTING}" == "1" && -f "${final_summary}" ]]; then
      echo "[unit ${index}/${total}] skip final existing: ${final_summary}"
      echo "skipped_existing" > "${status_file}"
      return 0
    fi

    read -r block_x block_y < <(parse_block_index "${unit_id}")

    echo "[unit ${index}/${total}] step 1/4 generate virtual well: BX=${block_x}, BY=${block_y}"
    "${PYTHON_CMD[@]}" "${VIRTUAL_WELL_SCRIPT}" \
      --block-x "${block_x}" \
      --block-y "${block_y}" \
      --output-root "${VIRTUAL_WELL_ROOT}" \
      --skip-existing

    echo "[unit ${index}/${total}] step 2/4 predict virtual fractures"
    "${PYTHON_CMD[@]}" "${VIRTUAL_FRACTURE_SCRIPT}" \
      --virtual-root "${VIRTUAL_WELL_ROOT}" \
      --output-root "${pred_root}" \
      --docx-path "${pred_docx}" \
      --include-unit-ids-json "[\"${unit_id}\"]" \
      --skip-existing "${SKIP_EXISTING}"

    echo "[unit ${index}/${total}] step 3/4 merge unit seed package"
    "${PYTHON_CMD[@]}" "${MERGE_PACKAGE_SCRIPT}" \
      --real-root "${REAL_ROOT}" \
      --virtual-fracture-root "${pred_root}" \
      --virtual-well-root "${VIRTUAL_WELL_ROOT}" \
      --output-root "${package_root}" \
      --docx-path "${merge_docx}" \
      --include-unit-ids-json "[\"${unit_id}\"]"

    echo "[unit ${index}/${total}] step 4/4 build final unit DFN"
    build_args=(
      "${BUILD_DFN_SCRIPT}"
      --unit-id "${unit_id}"
      --package-run-dir "${package_root}"
      --output-root "${FINAL_DFN_ROOT}"
    )
    if [[ "${OVERWRITE_FINAL}" == "1" ]]; then
      build_args+=(--overwrite)
    fi
    "${PYTHON_CMD[@]}" "${build_args[@]}"

    echo "[unit ${index}/${total}] done ${unit_id} at $(date '+%F %T')"
    echo "success" > "${status_file}"
  } > >(tee -a "${log_file}") 2>&1
}

echo "[supplement] start at $(date '+%F %T')"
echo "[supplement] repo=${REPO_ROOT}"
echo "[supplement] unit_list=${UNIT_LIST_CSV}"
echo "[supplement] unit_count=${#UNIT_IDS[@]}"
echo "[supplement] max_parallel=${MAX_PARALLEL}"
echo "[supplement] start_index=${START_INDEX}, end_index=${END_INDEX}"
echo "[supplement] shard_index=${SHARD_INDEX}, shard_count=${SHARD_COUNT}"
echo "[supplement] gpu_ids=${GPU_IDS:-none}"
echo "[supplement] log_root=${LOG_ROOT}"

if [[ "${MAX_PARALLEL}" -le 1 ]]; then
  total="${#UNIT_IDS[@]}"
  for idx in "${!UNIT_IDS[@]}"; do
    unit_id="${UNIT_IDS[${idx}]}"
    if ! run_unit "${unit_id}" "$((idx + 1))" "${total}"; then
      echo "failed" > "${STATUS_ROOT}/${unit_id}.status"
      echo "[supplement] failed unit=${unit_id}" >&2
      if [[ "${FAIL_FAST}" == "1" ]]; then
        exit 1
      fi
    fi
  done
else
  total="${#UNIT_IDS[@]}"
  parallel_failed=0
  pids=()
  for idx in "${!UNIT_IDS[@]}"; do
    while [[ "$(jobs -rp | wc -l)" -ge "${MAX_PARALLEL}" ]]; do
      sleep 5
    done
    unit_id="${UNIT_IDS[${idx}]}"
    (
      if ! run_unit "${unit_id}" "$((idx + 1))" "${total}"; then
        echo "failed" > "${STATUS_ROOT}/${unit_id}.status"
        exit 1
      fi
    ) &
    pids+=("$!")
  done
  for pid in "${pids[@]}"; do
    if ! wait "${pid}"; then
      parallel_failed=1
    fi
  done
fi

STATUS_ROOT_ENV="${STATUS_ROOT}" \
MAX_PARALLEL_ENV="${MAX_PARALLEL}" \
START_INDEX_ENV="${START_INDEX}" \
END_INDEX_ENV="${END_INDEX}" \
SHARD_INDEX_ENV="${SHARD_INDEX}" \
SHARD_COUNT_ENV="${SHARD_COUNT}" \
python -c '
import json
import os
from pathlib import Path

status_root = Path(os.environ["STATUS_ROOT_ENV"])
statuses = {}
for path in sorted(status_root.glob("*.status")):
    statuses[path.stem] = path.read_text(encoding="utf-8").strip()
summary = {
    "status_root": str(status_root),
    "max_parallel": int(os.environ.get("MAX_PARALLEL_ENV", "1")),
    "start_index": int(os.environ.get("START_INDEX_ENV", "1")),
    "end_index": int(os.environ.get("END_INDEX_ENV", "0")),
    "shard_index": int(os.environ.get("SHARD_INDEX_ENV", "0")),
    "shard_count": int(os.environ.get("SHARD_COUNT_ENV", "1")),
    "success_count": sum(v == "success" for v in statuses.values()),
    "skipped_existing_count": sum(v == "skipped_existing" for v in statuses.values()),
    "failed_count": sum(v == "failed" for v in statuses.values()),
    "statuses": statuses,
}
summary_path = status_root.parent / "supplement_blank_units_run_summary.json"
summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
print(json.dumps(summary, ensure_ascii=False, indent=2))
'

echo "[supplement] finished at $(date '+%F %T')"
if [[ "${MAX_PARALLEL}" -gt 1 && "${FAIL_FAST}" == "1" && "${parallel_failed:-0}" == "1" ]]; then
  exit 1
fi
